### ISSUE TITLE
Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:777)'),)

### ISSUE THREAD

**Issue by m0jtaba** [oasis-open/cti-taxii-client#24]
When I run the code below I am getting an SSLError the certificate that i am using is self signed:
```python
from taxii2client import Server
server = Server('https://192.168.56.100/taxii/', 'admin', 'letmein')

print(server.title)
```
Stack Trace:
``` python
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/urllib3/connectionpool.py", line 346, in _make_request
    self._validate_conn(conn)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/urllib3/connectionpool.py", line 850, in _validate_conn
    conn.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/urllib3/connection.py", line 326, in connect
    ssl_context=context)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/urllib3/util/ssl_.py", line 329, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 407, in wrap_socket
    _context=self, _session=session)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 814, in __init__
    self.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 1068, in do_handshake
    self._sslobj.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 689, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:777)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/urllib3/util/retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='192.168.56.100', port=443): Max retries exceeded with url: /taxii/ (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:777)'),))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "stix2Taxii.py", line 8, in <module>
    print(server.title)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/taxii2client/__init__.py", line 497, in title
    self._ensure_loaded()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/taxii2client/__init__.py", line 522, in _ensure_loaded
    self.refresh()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/taxii2client/__init__.py", line 525, in refresh
    response = self._conn.get(self.url, accept=MEDIA_TYPE_TAXII_V20)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/taxii2client/__init__.py", line 571, in get
    resp = self.session.get(url, headers=headers, params=params)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/requests/sessions.py", line 521, in get
    return self.request('GET', url, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/requests/adapters.py", line 506, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='192.168.56.100', port=443): Max retries exceeded with url: /taxii/ (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:777)'),))
```

**Comment by philroyer-phantom** [comment]
Can you work around this by making your own HTTPConnection and setting `verify=False`?

Using the latest from master...
```python
from taxii2client import Server, _HTTPConnection
server = Server('https://192.168.56.100/taxii/', conn=_HTTPConnection('https://192.168.56.100/taxii/', user='admin', password='letmein', verify=False))

print(server.title)
```

as a real fix we could expose the `verify` parameter to `Server.__init__()`

**Comment by m0jtaba** [comment]
@philroyer-phantom  tried your method and got the error below:

```
Traceback (most recent call last):
File "stix2Taxii.py", line 35, in <module>
server = Server('https://192.168.56.100/taxii/', conn=_HTTPConnection('https://192.168.56.100/taxii/', user='guest', password='guest', verify=False))
TypeError: __init__() got multiple values for argument 'user'
```

**Comment by emmanvg** [comment]
@m0jtaba, @philroyer-phantom was off by one argument in `_HTTPConnection`. Try this instead and see if it works:

``` Python
from taxii2client import Server, _HTTPConnection
server = Server('https://192.168.56.100/taxii/', conn=_HTTPConnection(user='admin', password='letmein', verify=False))

print(server.title)

**Comment by emmanvg** [comment]
Now, I do see @philroyer-phantom suggestion of exposing the `verify` parameter as a good suggestion. In addition there is currently a problem because we are passing the ``conn`` object to the value of the `verify` positional parameter in [here](https://github.com/oasis-open/cti-taxii-client/blob/master/taxii2client/__init__.py#L492).

**Comment by gtback** [comment]
I can't right now, but I can ask @robincover to add you to the maintainers of this library (and cti-taxii-server).

**Comment by m0jtaba** [comment]
@emmanvg I tried your suggestion got the following:

```
Traceback (most recent call last):
  File "test.pu", line 2, in <module>
    server = Server('https://192.168.56.100/taxii/', conn=_HTTPConnection(user='admin', password='letmein', verify=False))
TypeError: __init__() got an unexpected keyword argument 'verify'
```

However I see that you are fixing this by exposing verify. So when that is done then it should be all good?
