### ISSUE TITLE
Collection `verify` parameter doesn't get correctly processed

### ISSUE THREAD

**Issue by treyka** [oasis-open/cti-taxii-client#33]
@johnwunder asked me to test the TAXII2 server MITRE is launching to host ATT&CK and CAPEC content. Since this is currently using a certificate issued by MITRE's internal CA, certificate validation needs to be disabled.

Cf. the closed issues #17 and #24, the `verify` parameter doesn't get processed correctly. When I try:

`collection = Collection("https://obfuscated.mitre.org/taxii", verify=False)`

I get:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "~/cti-python-stix2/venv/lib/python3.5/site-packages/taxii2client/__init__.py", line 223, in __init__
    self._populate_fields(**kwargs)
TypeError: _populate_fields() got an unexpected keyword argument 'verify'
```
I can (of course) monkey-patch cti-taxii-client as an immediate workaround but this should be fixed.

**Comment by treyka** [comment]
In the course of monkey-patching, I noticed that I had installed cti-taxii-client from PyPI. When I did a pip install off the GitHub master branch the `verify` parameter worked correctly. I'm closing this issue but noting that PyPI needs to be updated. ^_^
