### ISSUE TITLE
Server() returns requests.exceptions.ConnectionError using proxies 

### ISSUE THREAD

**Issue by NikitaGautam** [oasis-open/cti-taxii-client#98]
According to this https://github.com/oasis-open/cti-taxii-client/issues/51 issue,  proxies are exposed to Server and ApiRoot objects. I'm trying to feed data from limo and I am using a valid proxy server to connect. I also tried using the sample code provided as a solution to connect to limo, but it does not work. 

However, when I try it with curl command, it works. 

```

from taxii2client.v20 import Server

def get_collection_threat_intelligence():
    # request to taxii server
    api_user = "guest"
    api_password = "guest"
    taxii_domain = "https://limo.anomali.com/api/v1/taxii2/taxii/"
    proxy = 'http://x.x.x.x:80'
    proxies = {
        'http': proxy
    }

    server_discovery = Server(url=taxii_domain, proxies=proxies, user=api_user, password=api_password, verify=False)

    print(server_discovery.api_roots)
    api_root = server_discovery.api_roots[0]
    # get collections
    print(api_root.collections)
    data = []
    for collection in api_root.collections:
        if collection.can_read:
            temp = {
                'id': collection.id,
                'title': collection.title
            }
            data.append(temp)
    # return collections
    result = {
        'data': data
    }
    return result


if __name__ == "__main__":
    result = get_collection_threat_intelligence()
```

The following error occurs: 

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/urllib3/connection.py", line 170, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/usr/local/lib/python3.7/dist-packages/urllib3/util/connection.py", line 73, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.7/socket.py", line 748, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/urllib3/connectionpool.py", line 706, in urlopen
    chunked=chunked,
  File "/usr/local/lib/python3.7/dist-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.7/dist-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.7/dist-packages/urllib3/connection.py", line 353, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.7/dist-packages/urllib3/connection.py", line 182, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f41df1c3d50>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/lib/python3.7/dist-packages/urllib3/connectionpool.py", line 756, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/usr/local/lib/python3.7/dist-packages/urllib3/util/retry.py", line 573, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='limo.anomali.com', port=443): Max retries exceeded with url: /api/v1/taxii2/taxii/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f41df1c3d50>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 42, in <module>
    result = get_collection_threat_intelligence()
  File "test.py", line 22, in get_collection_threat_intelligence
    print(server_discovery.api_roots)
  File "/usr/local/lib/python3.7/dist-packages/taxii2client/v20/__init__.py", line 709, in api_roots
    self._ensure_loaded()
  File "/usr/local/lib/python3.7/dist-packages/taxii2client/v20/__init__.py", line 725, in _ensure_loaded
    self.refresh()
  File "/usr/local/lib/python3.7/dist-packages/taxii2client/v20/__init__.py", line 760, in refresh
    response = self.__raw = self._conn.get(self.url)
  File "/usr/local/lib/python3.7/dist-packages/taxii2client/common.py", line 296, in get
    resp = self.session.get(url, headers=merged_headers, params=params)
  File "/usr/local/lib/python3.7/dist-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.7/dist-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)

Also, in the previous post the proxies are passed as follows:

   proxies = {
        'http': proxy,
        'https': proxy
    }

which throws requests.exceptions.SSLError: HTTPSConnectionPool

**Comment by zrush-mitre** [comment]
Hi @NikitaGautam,

I tried to recreate your issue in my own environment, but I was successfully able to connect to the TAXII server.

I noticed in the errors you posted, there's a connection refused error using HTTPS on port 443. This may be a clue to what's going on, as your proxy may be configured to expect one type of connection, but it is getting a different one.

You can try setting up your own TAXII server on your intranet and try to connect to that with your proxy to figure out where the error is coming from.

**Comment by rpiazza** [comment]
Closed for lack of discussion
